const tasks=[
    {
      "_id": "68c0e7df2cc2cd421f613e4e",
      "identifier": 4,
      "whole_identifier": "ZYK-4",
      "type": 5,
      "type_id": "62a31031a4426cd04da6dcb4",
      "project_id": "68c0e7ad2cc2cd421f613dbf",
      "created_by": "18ca07872f354c03b111bc8e0a08aadc",
      "created_at": 1757472735,
      "source": {
        "type": 1
      },
      "participants": [
        {
          "id": "18ca07872f354c03b111bc8e0a08aadc",
          "type": 1,
          "subscription": 40
        }
      ],
      "title": "缺陷",
      "parent_id": "68c0e7dc2cc2cd421f613e43",
      "parent_ids": [
        "68c0e7bc2cc2cd421f613e2e",
        "68c0e7da2cc2cd421f613e38",
        "68c0e7dc2cc2cd421f613e43"
      ],
      "due": {
        "date": 1757260799,
        "with_time": 0
      },
      "phase": {
        "ref_id": null
      },
      "state_id": "62a31031a4426cd04da6dcb6",
      "state_type": 1,
      "state_updated_at": 1757472735,
      "is_completed": 0,
      "completed_at": null,
      "completed_by": null,
      "properties": {
        "estimated_workload": 12,
        "remaining_workload": 12,
        "reported_workload": null,
        "board_id": null,
        "swimlane_id": null,
        "entry_id": null,
        "entry_status": null,
        "entry_position": null,
        "operation_time": 1757472735,
        "workload_ss_armh": null,
        "workload_ss_emh": 18,
        "workload_ss_ermh": 18,
        "workload_ss_pbr": 0,
        "progress_by_remaining": 0,
        "severity": null,
        "story_points": null,
        "iteration": null,
        "replay_version": null,
        "reappear_probability": null,
        "bug_type": null,
        "reason": null,
        "version": null,
        "solution": null,
        "replay_step": null,
        "zhichixuanzefu": null,
        "pingfen0621": null,
        "lianjie0621": null,
        "jindu0621_1": null,
        "xialaduoxuan": []
      },
      "position": 65536,
      "short_id": "2iTMxm5R",
      "updated_at": 1757473670,
      "updated_by": "18ca07872f354c03b111bc8e0a08aadc",
      "is_deleted": 0,
      "is_archived": 0,
      "team": "62a31031fbadbd0d9adc51cf",
      "assignee": "1a8f7eb205de442a87cdf9c24c532145",
      "start": {
        "date": 1756828800,
        "with_time": 0
      },
      "priority": null,
      "tags": [],
      "description": null,
      "attachment_count": 0,
      "user_group_participants": [],
      "comment_count": 0,
      "likes": [],
      "like_count": 0,
      "imported_at": null,
      "imported_by": null,
      "enter_iteration_at": null,
      "resources": [],
      "review_result_state": 0,
      "_updated_at": 1757473754103,
      "version_id": "68c0e7df2cc2cd421f613e4f",
      "version_identifier": 1,
      "relation_total": {
        "work_item": 2,
        "objective": 0,
        "idea": 0,
        "ticket": 0,
        "test_case": 0,
        "test_run": 0,
        "page": 0
      },
      "assign_at": 1757473601,
      "assignor": "18ca07872f354c03b111bc8e0a08aadc",
      "_v": 11,
      "permissions": "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "scope": {
        "project_template_type": "hybrid",
        "work_item_type": "62a31031a4426cd04da6dcb4"
      },
      "extend_property_keys": [
        "remaining_workload",
        "estimated_workload",
        "reported_workload",
        "progress_by_remaining",
        "child_progress",
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "sorted_property_keys": [
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "state_dwell_time": null,
      "real_type_group": "bug",
      "type_group": 3,
      "link_count": 0,
      "quick_operation_actions": {
        "parent": 1,
        "state": 1,
        "assignee": 1,
        "start": 1,
        "due": 1,
        "priority": 1,
        "tag": 1,
        "copy": 1,
        "move": 1,
        "archive": 1,
        "active": 0,
        "delete": 1,
        "sprint": 0,
        "version": 1,
        "relate": 1,
        "board": 0
      },
      "version_name": "v1",
      "version_description": "Initialization & creation",
      "principal_version": "v1",
      "is_latest_version": 1,
      "property_permissions": {
        "title": 1,
        "identifier": 1,
        "type": 1,
        "state_id": 1,
        "assignee": 1,
        "parent_id": 1,
        "start": 1,
        "due": 1,
        "participants": 1,
        "created_at": 1,
        "created_by": 1,
        "updated_at": 1,
        "updated_by": 1,
        "completed_at": 1,
        "completed_by": 1,
        "archived_at": 1,
        "archived_by": 1,
        "deleted_at": 1,
        "deleted_by": 1,
        "state_dwell_time": 0,
        "state_type": 1,
        "attachments": 1,
        "review_result_state": 1,
        "project_id": 1,
        "reported_workload": 1,
        "remaining_workload": 1,
        "estimated_workload": 1,
        "progress_by_remaining": 1,
        "board_id": 1,
        "priority": 1,
        "severity": 1,
        "story_points": 1,
        "iteration": 1,
        "replay_version": 1,
        "reappear_probability": 1,
        "bug_type": 1,
        "reason": 1,
        "version": 1,
        "solution": 1,
        "tags": 1,
        "description": 1,
        "idea_count": 1,
        "work_item_count": 1,
        "ticket_count": 1,
        "test_case_count": 1,
        "objective_count": 1,
        "replay_step": 1,
        "phase": 1,
        "zhichixuanzefu": 1,
        "pingfen0621": 1,
        "lianjie0621": 1,
        "jindu0621_1": 1,
        "xialaduoxuan": 1,
        "child_progress": 1,
        "dependency_work_item": 1,
        "principal_version": 1,
        "deliverables": 1
      },
      "deliverables": {
        "total": 0,
        "submitted": 0
      },
      "child_ids": [
        "68c0e7e22cc2cd421f613e59"
      ],
      "child_progress": 100,
      "child_completed_count": 1,
      "child_count": 1
    },
    {
      "_id": "68c0e7e22cc2cd421f613e59",
      "identifier": 5,
      "whole_identifier": "ZYK-5",
      "type": 5,
      "type_id": "62a31031a4426cd04da6dcb4",
      "project_id": "68c0e7ad2cc2cd421f613dbf",
      "created_by": "18ca07872f354c03b111bc8e0a08aadc",
      "created_at": 1757472738,
      "source": {
        "type": 1
      },
      "participants": [
        {
          "id": "18ca07872f354c03b111bc8e0a08aadc",
          "type": 1,
          "subscription": 40
        }
      ],
      "title": "缺陷",
      "parent_id": "68c0e7df2cc2cd421f613e4e",
      "parent_ids": [
        "68c0e7bc2cc2cd421f613e2e",
        "68c0e7da2cc2cd421f613e38",
        "68c0e7dc2cc2cd421f613e43",
        "68c0e7df2cc2cd421f613e4e"
      ],
      "due": {
        "date": 1757692799,
        "with_time": 0
      },
      "phase": {
        "ref_id": null
      },
      "state_id": "62a31031a4426cd04da6dcba",
      "state_type": 3,
      "state_updated_at": 1757581321,
      "is_completed": 1,
      "completed_at": 1757581321,
      "completed_by": "18ca07872f354c03b111bc8e0a08aadc",
      "properties": {
        "estimated_workload": 6,
        "remaining_workload": 6,
        "reported_workload": null,
        "board_id": null,
        "swimlane_id": null,
        "entry_id": null,
        "entry_status": null,
        "entry_position": null,
        "operation_time": 1757472738,
        "progress_by_remaining": 0,
        "workload_ss_armh": null,
        "workload_ss_emh": 6,
        "workload_ss_ermh": 6,
        "workload_ss_pbr": 0,
        "severity": null,
        "story_points": null,
        "iteration": null,
        "replay_version": null,
        "reappear_probability": null,
        "bug_type": null,
        "reason": null,
        "version": null,
        "solution": null,
        "replay_step": null,
        "zhichixuanzefu": null,
        "pingfen0621": null,
        "lianjie0621": null,
        "jindu0621_1": null,
        "xialaduoxuan": []
      },
      "position": 65536,
      "short_id": "dOnV6ZBl",
      "updated_at": 1757584199,
      "updated_by": "18ca07872f354c03b111bc8e0a08aadc",
      "is_deleted": 0,
      "is_archived": 0,
      "team": "62a31031fbadbd0d9adc51cf",
      "assignee": "18ca07872f354c03b111bc8e0a08aadc",
      "start": {
        "date": 1756742400,
        "with_time": 0
      },
      "priority": null,
      "tags": [],
      "description": null,
      "attachment_count": 0,
      "user_group_participants": [],
      "comment_count": 0,
      "likes": [],
      "like_count": 0,
      "imported_at": null,
      "imported_by": null,
      "enter_iteration_at": null,
      "resources": [],
      "review_result_state": 0,
      "_updated_at": 1757584199628,
      "version_id": "68c0e7e22cc2cd421f613e5a",
      "version_identifier": 1,
      "relation_total": {
        "work_item": 2,
        "objective": 0,
        "idea": 0,
        "ticket": 0,
        "test_case": 0,
        "test_run": 0,
        "page": 0
      },
      "assign_at": 1757473619,
      "assignor": "18ca07872f354c03b111bc8e0a08aadc",
      "_v": 11,
      "permissions": "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "scope": {
        "project_template_type": "hybrid",
        "work_item_type": "62a31031a4426cd04da6dcb4"
      },
      "extend_property_keys": [
        "remaining_workload",
        "estimated_workload",
        "reported_workload",
        "progress_by_remaining",
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "sorted_property_keys": [
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "state_dwell_time": null,
      "real_type_group": "bug",
      "type_group": 3,
      "link_count": 0,
      "quick_operation_actions": {
        "parent": 1,
        "state": 1,
        "assignee": 1,
        "start": 1,
        "due": 1,
        "priority": 1,
        "tag": 1,
        "copy": 1,
        "move": 1,
        "archive": 1,
        "active": 0,
        "delete": 1,
        "sprint": 0,
        "version": 1,
        "relate": 1,
        "board": 0
      },
      "version_name": "v1",
      "version_description": "Initialization & creation",
      "principal_version": "v1",
      "is_latest_version": 1,
      "property_permissions": {
        "title": 1,
        "identifier": 1,
        "type": 1,
        "state_id": 1,
        "assignee": 1,
        "parent_id": 1,
        "start": 1,
        "due": 1,
        "participants": 1,
        "created_at": 1,
        "created_by": 1,
        "updated_at": 1,
        "updated_by": 1,
        "completed_at": 1,
        "completed_by": 1,
        "archived_at": 1,
        "archived_by": 1,
        "deleted_at": 1,
        "deleted_by": 1,
        "state_dwell_time": 0,
        "state_type": 1,
        "attachments": 1,
        "review_result_state": 1,
        "project_id": 1,
        "reported_workload": 1,
        "remaining_workload": 1,
        "estimated_workload": 1,
        "progress_by_remaining": 1,
        "board_id": 1,
        "priority": 1,
        "severity": 1,
        "story_points": 1,
        "iteration": 1,
        "replay_version": 1,
        "reappear_probability": 1,
        "bug_type": 1,
        "reason": 1,
        "version": 1,
        "solution": 1,
        "tags": 1,
        "description": 1,
        "idea_count": 1,
        "work_item_count": 1,
        "ticket_count": 1,
        "test_case_count": 1,
        "objective_count": 1,
        "replay_step": 1,
        "phase": 1,
        "zhichixuanzefu": 1,
        "pingfen0621": 1,
        "lianjie0621": 1,
        "jindu0621_1": 1,
        "xialaduoxuan": 1,
        "child_progress": 1,
        "dependency_work_item": 1,
        "principal_version": 1,
        "deliverables": 1
      },
      "deliverables": {
        "total": 0,
        "submitted": 0
      },
      "child_ids": [],
      "child_progress": 0,
      "child_completed_count": 0,
      "child_count": 0
    },
    {
      "_id": "68c0e7e62cc2cd421f613e65",
      "type": 5,
      "type_id": "62a31031a4426cd04da6dcb4",
      "title": "缺陷",
      "project_id": "68c0e7ad2cc2cd421f613dbf",
      "position": 65536,
      "properties": {
        "board_id": null,
        "severity": null,
        "story_points": null,
        "iteration": null,
        "replay_version": [],
        "reappear_probability": null,
        "bug_type": null,
        "reason": null,
        "version": [],
        "solution": null,
        "replay_step": null,
        "zhichixuanzefu": null,
        "pingfen0621": null,
        "lianjie0621": null,
        "jindu0621_1": null,
        "estimated_workload": 2,
        "remaining_workload": 2,
        "workload_ss_emh": 6,
        "workload_ss_ermh": 6,
        "reported_workload": null,
        "workload": {
          "reported_total": 0,
          "remaining": 0,
          "estimated": {
            "duration": 0,
            "estimated_at": 1757472742,
            "estimated_by": null
          }
        },
        "operation_time": 1757472742,
        "swimlane_id": null,
        "entry_id": null,
        "entry_status": null,
        "entry_position": null,
        "phase": null,
        "workload_ss_armh": null,
        "workload_ss_pbr": 0,
        "progress_by_remaining": 0,
        "xialaduoxuan": []
      },
      "parent_id": "68c0e7e62cc2cd421f613e64",
      "parent_ids": [
        "68c0e7e62cc2cd421f613e62",
        "68c0e7e62cc2cd421f613e63",
        "68c0e7e62cc2cd421f613e64"
      ],
      "identifier": 9,
      "whole_identifier": "ZYK-9",
      "assignee": "f2a2f4477e57431b975b50bd3f04e075",
      "participants": [
        {
          "id": "18ca07872f354c03b111bc8e0a08aadc",
          "type": 1,
          "subscription": 40
        }
      ],
      "start": {
        "date": 1756915200,
        "with_time": 0
      },
      "due": {
        "date": 1757692799,
        "with_time": 0
      },
      "priority": null,
      "tags": [],
      "description": null,
      "phase": {
        "ref_id": null
      },
      "state_dwell_time": null,
      "state_id": "62a31031a4426cd04da6dcb6",
      "state_type": 1,
      "state_updated_at": 1757472742,
      "is_completed": 0,
      "completed_at": null,
      "completed_by": null,
      "comment_count": 0,
      "links": [],
      "attachment_count": 0,
      "user_group_participants": [],
      "source": {
        "type": 2,
        "from": "68c0e7df2cc2cd421f613e4e"
      },
      "short_id": "E3fdipxy",
      "created_at": 1757472742,
      "created_by": "18ca07872f354c03b111bc8e0a08aadc",
      "updated_at": 1757574549,
      "updated_by": "18ca07872f354c03b111bc8e0a08aadc",
      "is_deleted": 0,
      "is_archived": 0,
      "team": "62a31031fbadbd0d9adc51cf",
      "likes": [],
      "like_count": 0,
      "imported_at": null,
      "imported_by": null,
      "enter_iteration_at": null,
      "resources": [],
      "review_result_state": 0,
      "_updated_at": 1758681736552,
      "version_id": "68c0e7e62cc2cd421f613e88",
      "version_identifier": 1,
      "relation_total": {
        "work_item": 1,
        "objective": 0,
        "idea": 0,
        "ticket": 0,
        "test_case": 0,
        "test_run": 0,
        "page": 0
      },
      "assign_at": 1757473614,
      "assignor": "18ca07872f354c03b111bc8e0a08aadc",
      "_v": 11,
      "permissions": "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "scope": {
        "project_template_type": "hybrid",
        "work_item_type": "62a31031a4426cd04da6dcb4"
      },
      "extend_property_keys": [
        "remaining_workload",
        "estimated_workload",
        "reported_workload",
        "progress_by_remaining",
        "child_progress",
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "sorted_property_keys": [
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "real_type_group": "bug",
      "type_group": 3,
      "link_count": 0,
      "quick_operation_actions": {
        "parent": 1,
        "state": 1,
        "assignee": 1,
        "start": 1,
        "due": 1,
        "priority": 1,
        "tag": 1,
        "copy": 1,
        "move": 1,
        "archive": 1,
        "active": 0,
        "delete": 1,
        "sprint": 0,
        "version": 1,
        "relate": 1,
        "board": 0
      },
      "version_name": "v1",
      "version_description": "Initialization & creation",
      "principal_version": "v1",
      "is_latest_version": 1,
      "property_permissions": {
        "title": 1,
        "identifier": 1,
        "type": 1,
        "state_id": 1,
        "assignee": 1,
        "parent_id": 1,
        "start": 1,
        "due": 1,
        "participants": 1,
        "created_at": 1,
        "created_by": 1,
        "updated_at": 1,
        "updated_by": 1,
        "completed_at": 1,
        "completed_by": 1,
        "archived_at": 1,
        "archived_by": 1,
        "deleted_at": 1,
        "deleted_by": 1,
        "state_dwell_time": 0,
        "state_type": 1,
        "attachments": 1,
        "review_result_state": 1,
        "project_id": 1,
        "reported_workload": 1,
        "remaining_workload": 1,
        "estimated_workload": 1,
        "progress_by_remaining": 1,
        "board_id": 1,
        "priority": 1,
        "severity": 1,
        "story_points": 1,
        "iteration": 1,
        "replay_version": 1,
        "reappear_probability": 1,
        "bug_type": 1,
        "reason": 1,
        "version": 1,
        "solution": 1,
        "tags": 1,
        "description": 1,
        "idea_count": 1,
        "work_item_count": 1,
        "ticket_count": 1,
        "test_case_count": 1,
        "objective_count": 1,
        "replay_step": 1,
        "phase": 1,
        "zhichixuanzefu": 1,
        "pingfen0621": 1,
        "lianjie0621": 1,
        "jindu0621_1": 1,
        "xialaduoxuan": 1,
        "child_progress": 1,
        "dependency_work_item": 1,
        "principal_version": 1,
        "deliverables": 1
      },
      "deliverables": {
        "total": 0,
        "submitted": 0
      },
      "child_ids": [
        "68c0e7e62cc2cd421f613e66"
      ],
      "child_progress": 0,
      "child_completed_count": 0,
      "child_count": 1
    },
    {
      "_id": "68c0e7e62cc2cd421f613e66",
      "type": 5,
      "type_id": "62a31031a4426cd04da6dcb4",
      "title": "缺陷",
      "project_id": "68c0e7ad2cc2cd421f613dbf",
      "position": 65536,
      "properties": {
        "board_id": null,
        "severity": null,
        "story_points": null,
        "iteration": null,
        "replay_version": [],
        "reappear_probability": null,
        "bug_type": null,
        "reason": null,
        "version": [],
        "solution": null,
        "replay_step": null,
        "zhichixuanzefu": null,
        "pingfen0621": null,
        "lianjie0621": null,
        "jindu0621_1": null,
        "estimated_workload": 4,
        "remaining_workload": 4,
        "workload_ss_emh": 4,
        "workload_ss_ermh": 4,
        "reported_workload": null,
        "workload": {
          "reported_total": 0,
          "remaining": 0,
          "estimated": {
            "duration": 0,
            "estimated_at": 1757472742,
            "estimated_by": null
          }
        },
        "operation_time": 1757472742,
        "swimlane_id": null,
        "entry_id": null,
        "entry_status": null,
        "entry_position": null,
        "phase": null,
        "progress_by_remaining": 0,
        "workload_ss_armh": null,
        "workload_ss_pbr": 0,
        "xialaduoxuan": []
      },
      "parent_id": "68c0e7e62cc2cd421f613e65",
      "parent_ids": [
        "68c0e7e62cc2cd421f613e62",
        "68c0e7e62cc2cd421f613e63",
        "68c0e7e62cc2cd421f613e64",
        "68c0e7e62cc2cd421f613e65"
      ],
      "identifier": 10,
      "whole_identifier": "ZYK-10",
      "assignee": "1a8f7eb205de442a87cdf9c24c532145",
      "participants": [
        {
          "id": "18ca07872f354c03b111bc8e0a08aadc",
          "type": 1,
          "subscription": 40
        }
      ],
      "start": {
        "date": 1757347200,
        "with_time": 0
      },
      "due": {
        "date": 1757865599,
        "with_time": 0
      },
      "priority": null,
      "tags": [],
      "description": null,
      "phase": {
        "ref_id": null
      },
      "state_dwell_time": null,
      "state_id": "62a31031a4426cd04da6dcb6",
      "state_type": 1,
      "state_updated_at": 1757472742,
      "is_completed": 0,
      "completed_at": null,
      "completed_by": null,
      "comment_count": 0,
      "links": [],
      "attachment_count": 0,
      "user_group_participants": [],
      "source": {
        "type": 2,
        "from": "68c0e7e22cc2cd421f613e59"
      },
      "short_id": "NhYIcdGI",
      "created_at": 1757472742,
      "created_by": "18ca07872f354c03b111bc8e0a08aadc",
      "updated_at": 1757473681,
      "updated_by": "18ca07872f354c03b111bc8e0a08aadc",
      "is_deleted": 0,
      "is_archived": 0,
      "team": "62a31031fbadbd0d9adc51cf",
      "likes": [],
      "like_count": 0,
      "imported_at": null,
      "imported_by": null,
      "enter_iteration_at": null,
      "resources": [],
      "review_result_state": 0,
      "_updated_at": 1758681736552,
      "version_id": "68c0e7e62cc2cd421f613e89",
      "version_identifier": 1,
      "relation_total": {
        "work_item": 1,
        "objective": 0,
        "idea": 0,
        "ticket": 0,
        "test_case": 0,
        "test_run": 0,
        "page": 0
      },
      "assign_at": 1757473607,
      "assignor": "18ca07872f354c03b111bc8e0a08aadc",
      "_v": 11,
      "permissions": "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "scope": {
        "project_template_type": "hybrid",
        "work_item_type": "62a31031a4426cd04da6dcb4"
      },
      "extend_property_keys": [
        "remaining_workload",
        "estimated_workload",
        "reported_workload",
        "progress_by_remaining",
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "sorted_property_keys": [
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "real_type_group": "bug",
      "type_group": 3,
      "link_count": 0,
      "quick_operation_actions": {
        "parent": 1,
        "state": 1,
        "assignee": 1,
        "start": 1,
        "due": 1,
        "priority": 1,
        "tag": 1,
        "copy": 1,
        "move": 1,
        "archive": 1,
        "active": 0,
        "delete": 1,
        "sprint": 0,
        "version": 1,
        "relate": 1,
        "board": 0
      },
      "version_name": "v1",
      "version_description": "Initialization & creation",
      "principal_version": "v1",
      "is_latest_version": 1,
      "property_permissions": {
        "title": 1,
        "identifier": 1,
        "type": 1,
        "state_id": 1,
        "assignee": 1,
        "parent_id": 1,
        "start": 1,
        "due": 1,
        "participants": 1,
        "created_at": 1,
        "created_by": 1,
        "updated_at": 1,
        "updated_by": 1,
        "completed_at": 1,
        "completed_by": 1,
        "archived_at": 1,
        "archived_by": 1,
        "deleted_at": 1,
        "deleted_by": 1,
        "state_dwell_time": 0,
        "state_type": 1,
        "attachments": 1,
        "review_result_state": 1,
        "project_id": 1,
        "reported_workload": 1,
        "remaining_workload": 1,
        "estimated_workload": 1,
        "progress_by_remaining": 1,
        "board_id": 1,
        "priority": 1,
        "severity": 1,
        "story_points": 1,
        "iteration": 1,
        "replay_version": 1,
        "reappear_probability": 1,
        "bug_type": 1,
        "reason": 1,
        "version": 1,
        "solution": 1,
        "tags": 1,
        "description": 1,
        "idea_count": 1,
        "work_item_count": 1,
        "ticket_count": 1,
        "test_case_count": 1,
        "objective_count": 1,
        "replay_step": 1,
        "phase": 1,
        "zhichixuanzefu": 1,
        "pingfen0621": 1,
        "lianjie0621": 1,
        "jindu0621_1": 1,
        "xialaduoxuan": 1,
        "child_progress": 1,
        "dependency_work_item": 1,
        "principal_version": 1,
        "deliverables": 1
      },
      "deliverables": {
        "total": 0,
        "submitted": 0
      },
      "child_ids": [],
      "child_progress": 0,
      "child_completed_count": 0,
      "child_count": 0
    },
    {
      "_id": "68c0e7ef2cc2cd421f613eaa",
      "type": 5,
      "type_id": "62a31031a4426cd04da6dcb4",
      "title": "缺陷",
      "project_id": "68c0e7ad2cc2cd421f613dbf",
      "position": 65536,
      "properties": {
        "board_id": null,
        "severity": null,
        "story_points": null,
        "iteration": null,
        "replay_version": [],
        "reappear_probability": null,
        "bug_type": null,
        "reason": null,
        "version": [],
        "solution": null,
        "replay_step": null,
        "zhichixuanzefu": null,
        "pingfen0621": null,
        "lianjie0621": null,
        "jindu0621_1": null,
        "estimated_workload": 6,
        "remaining_workload": 6,
        "workload_ss_emh": 8,
        "workload_ss_ermh": 8,
        "reported_workload": null,
        "workload": {
          "reported_total": 0,
          "remaining": 0,
          "estimated": {
            "duration": 0,
            "estimated_at": 1757472751,
            "estimated_by": null
          }
        },
        "operation_time": 1757472751,
        "swimlane_id": null,
        "entry_id": null,
        "entry_status": null,
        "entry_position": null,
        "phase": null,
        "workload_ss_armh": null,
        "workload_ss_pbr": 0,
        "progress_by_remaining": 0,
        "xialaduoxuan": []
      },
      "parent_id": "68c0e7ef2cc2cd421f613ea9",
      "parent_ids": [
        "68c0e7ef2cc2cd421f613ea7",
        "68c0e7ef2cc2cd421f613ea8",
        "68c0e7ef2cc2cd421f613ea9"
      ],
      "identifier": 14,
      "whole_identifier": "ZYK-14",
      "assignee": "18ca07872f354c03b111bc8e0a08aadc",
      "participants": [
        {
          "id": "18ca07872f354c03b111bc8e0a08aadc",
          "type": 1,
          "subscription": 40
        }
      ],
      "start": {
        "date": 1759593600,
        "with_time": 0
      },
      "due": {
        "date": 1760111999,
        "with_time": 0
      },
      "priority": null,
      "tags": [],
      "description": null,
      "phase": {
        "ref_id": null
      },
      "state_dwell_time": null,
      "state_id": "62a31031a4426cd04da6dcb6",
      "state_type": 1,
      "state_updated_at": 1757472751,
      "is_completed": 0,
      "completed_at": null,
      "completed_by": null,
      "comment_count": 0,
      "links": [],
      "attachment_count": 0,
      "user_group_participants": [],
      "source": {
        "type": 2,
        "from": "68c0e7df2cc2cd421f613e4e"
      },
      "short_id": "ToW8L1uM",
      "created_at": 1757472751,
      "created_by": "18ca07872f354c03b111bc8e0a08aadc",
      "updated_at": 1757474266,
      "updated_by": "18ca07872f354c03b111bc8e0a08aadc",
      "is_deleted": 0,
      "is_archived": 0,
      "team": "62a31031fbadbd0d9adc51cf",
      "likes": [],
      "like_count": 0,
      "imported_at": null,
      "imported_by": null,
      "enter_iteration_at": null,
      "resources": [],
      "review_result_state": 0,
      "_updated_at": 1758681736552,
      "version_id": "68c0e7ef2cc2cd421f613ecd",
      "version_identifier": 1,
      "relation_total": {
        "work_item": 2,
        "objective": 0,
        "idea": 0,
        "ticket": 0,
        "test_case": 0,
        "test_run": 0,
        "page": 0
      },
      "assign_at": 1757474220,
      "assignor": "18ca07872f354c03b111bc8e0a08aadc",
      "_v": 11,
      "permissions": "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "scope": {
        "project_template_type": "hybrid",
        "work_item_type": "62a31031a4426cd04da6dcb4"
      },
      "extend_property_keys": [
        "remaining_workload",
        "estimated_workload",
        "reported_workload",
        "progress_by_remaining",
        "child_progress",
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "sorted_property_keys": [
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "real_type_group": "bug",
      "type_group": 3,
      "link_count": 0,
      "quick_operation_actions": {
        "parent": 1,
        "state": 1,
        "assignee": 1,
        "start": 1,
        "due": 1,
        "priority": 1,
        "tag": 1,
        "copy": 1,
        "move": 1,
        "archive": 1,
        "active": 0,
        "delete": 1,
        "sprint": 0,
        "version": 1,
        "relate": 1,
        "board": 0
      },
      "version_name": "v1",
      "version_description": "Initialization & creation",
      "principal_version": "v1",
      "is_latest_version": 1,
      "property_permissions": {
        "title": 1,
        "identifier": 1,
        "type": 1,
        "state_id": 1,
        "assignee": 1,
        "parent_id": 1,
        "start": 1,
        "due": 1,
        "participants": 1,
        "created_at": 1,
        "created_by": 1,
        "updated_at": 1,
        "updated_by": 1,
        "completed_at": 1,
        "completed_by": 1,
        "archived_at": 1,
        "archived_by": 1,
        "deleted_at": 1,
        "deleted_by": 1,
        "state_dwell_time": 0,
        "state_type": 1,
        "attachments": 1,
        "review_result_state": 1,
        "project_id": 1,
        "reported_workload": 1,
        "remaining_workload": 1,
        "estimated_workload": 1,
        "progress_by_remaining": 1,
        "board_id": 1,
        "priority": 1,
        "severity": 1,
        "story_points": 1,
        "iteration": 1,
        "replay_version": 1,
        "reappear_probability": 1,
        "bug_type": 1,
        "reason": 1,
        "version": 1,
        "solution": 1,
        "tags": 1,
        "description": 1,
        "idea_count": 1,
        "work_item_count": 1,
        "ticket_count": 1,
        "test_case_count": 1,
        "objective_count": 1,
        "replay_step": 1,
        "phase": 1,
        "zhichixuanzefu": 1,
        "pingfen0621": 1,
        "lianjie0621": 1,
        "jindu0621_1": 1,
        "xialaduoxuan": 1,
        "child_progress": 1,
        "dependency_work_item": 1,
        "principal_version": 1,
        "deliverables": 1
      },
      "deliverables": {
        "total": 0,
        "submitted": 0
      },
      "child_ids": [
        "68c0e7ef2cc2cd421f613eab"
      ],
      "child_progress": 0,
      "child_completed_count": 0,
      "child_count": 1
    },
    {
      "_id": "68c0e7ef2cc2cd421f613eab",
      "type": 5,
      "type_id": "62a31031a4426cd04da6dcb4",
      "title": "缺陷",
      "project_id": "68c0e7ad2cc2cd421f613dbf",
      "position": 65536,
      "properties": {
        "board_id": null,
        "severity": null,
        "story_points": null,
        "iteration": null,
        "replay_version": [],
        "reappear_probability": null,
        "bug_type": null,
        "reason": null,
        "version": [],
        "solution": null,
        "replay_step": null,
        "zhichixuanzefu": null,
        "pingfen0621": null,
        "lianjie0621": null,
        "jindu0621_1": null,
        "estimated_workload": 2,
        "remaining_workload": 2,
        "workload_ss_emh": 2,
        "workload_ss_ermh": 2,
        "reported_workload": null,
        "workload": {
          "reported_total": 0,
          "remaining": 0,
          "estimated": {
            "duration": 0,
            "estimated_at": 1757472751,
            "estimated_by": null
          }
        },
        "operation_time": 1757472751,
        "swimlane_id": null,
        "entry_id": null,
        "entry_status": null,
        "entry_position": null,
        "phase": null,
        "progress_by_remaining": 0,
        "workload_ss_armh": null,
        "workload_ss_pbr": 0,
        "xialaduoxuan": []
      },
      "parent_id": "68c0e7ef2cc2cd421f613eaa",
      "parent_ids": [
        "68c0e7ef2cc2cd421f613ea7",
        "68c0e7ef2cc2cd421f613ea8",
        "68c0e7ef2cc2cd421f613ea9",
        "68c0e7ef2cc2cd421f613eaa"
      ],
      "identifier": 15,
      "whole_identifier": "ZYK-15",
      "assignee": "b4c903caafbf40258c3449259286cbe5",
      "participants": [
        {
          "id": "18ca07872f354c03b111bc8e0a08aadc",
          "type": 1,
          "subscription": 40
        }
      ],
      "start": {
        "date": 1760371200,
        "with_time": 0
      },
      "due": {
        "date": 1760889599,
        "with_time": 0
      },
      "priority": null,
      "tags": [],
      "description": null,
      "phase": {
        "ref_id": null
      },
      "state_dwell_time": null,
      "state_id": "62a31031a4426cd04da6dcb6",
      "state_type": 1,
      "state_updated_at": 1757472751,
      "is_completed": 0,
      "completed_at": null,
      "completed_by": null,
      "comment_count": 0,
      "links": [],
      "attachment_count": 0,
      "user_group_participants": [],
      "source": {
        "type": 2,
        "from": "68c0e7e22cc2cd421f613e59"
      },
      "short_id": "GohJkCCJ",
      "created_at": 1757472751,
      "created_by": "18ca07872f354c03b111bc8e0a08aadc",
      "updated_at": 1757474273,
      "updated_by": "18ca07872f354c03b111bc8e0a08aadc",
      "is_deleted": 0,
      "is_archived": 0,
      "team": "62a31031fbadbd0d9adc51cf",
      "likes": [],
      "like_count": 0,
      "imported_at": null,
      "imported_by": null,
      "enter_iteration_at": null,
      "resources": [],
      "review_result_state": 0,
      "_updated_at": 1758681736552,
      "version_id": "68c0e7ef2cc2cd421f613ece",
      "version_identifier": 1,
      "relation_total": {
        "work_item": 2,
        "objective": 0,
        "idea": 0,
        "ticket": 0,
        "test_case": 0,
        "test_run": 0,
        "page": 0
      },
      "assign_at": 1757474229,
      "assignor": "18ca07872f354c03b111bc8e0a08aadc",
      "_v": 11,
      "permissions": "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "scope": {
        "project_template_type": "hybrid",
        "work_item_type": "62a31031a4426cd04da6dcb4"
      },
      "extend_property_keys": [
        "remaining_workload",
        "estimated_workload",
        "reported_workload",
        "progress_by_remaining",
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "sorted_property_keys": [
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "real_type_group": "bug",
      "type_group": 3,
      "link_count": 0,
      "quick_operation_actions": {
        "parent": 1,
        "state": 1,
        "assignee": 1,
        "start": 1,
        "due": 1,
        "priority": 1,
        "tag": 1,
        "copy": 1,
        "move": 1,
        "archive": 1,
        "active": 0,
        "delete": 1,
        "sprint": 0,
        "version": 1,
        "relate": 1,
        "board": 0
      },
      "version_name": "v1",
      "version_description": "Initialization & creation",
      "principal_version": "v1",
      "is_latest_version": 1,
      "property_permissions": {
        "title": 1,
        "identifier": 1,
        "type": 1,
        "state_id": 1,
        "assignee": 1,
        "parent_id": 1,
        "start": 1,
        "due": 1,
        "participants": 1,
        "created_at": 1,
        "created_by": 1,
        "updated_at": 1,
        "updated_by": 1,
        "completed_at": 1,
        "completed_by": 1,
        "archived_at": 1,
        "archived_by": 1,
        "deleted_at": 1,
        "deleted_by": 1,
        "state_dwell_time": 0,
        "state_type": 1,
        "attachments": 1,
        "review_result_state": 1,
        "project_id": 1,
        "reported_workload": 1,
        "remaining_workload": 1,
        "estimated_workload": 1,
        "progress_by_remaining": 1,
        "board_id": 1,
        "priority": 1,
        "severity": 1,
        "story_points": 1,
        "iteration": 1,
        "replay_version": 1,
        "reappear_probability": 1,
        "bug_type": 1,
        "reason": 1,
        "version": 1,
        "solution": 1,
        "tags": 1,
        "description": 1,
        "idea_count": 1,
        "work_item_count": 1,
        "ticket_count": 1,
        "test_case_count": 1,
        "objective_count": 1,
        "replay_step": 1,
        "phase": 1,
        "zhichixuanzefu": 1,
        "pingfen0621": 1,
        "lianjie0621": 1,
        "jindu0621_1": 1,
        "xialaduoxuan": 1,
        "child_progress": 1,
        "dependency_work_item": 1,
        "principal_version": 1,
        "deliverables": 1
      },
      "deliverables": {
        "total": 0,
        "submitted": 0
      },
      "child_ids": [],
      "child_progress": 0,
      "child_completed_count": 0,
      "child_count": 0
    },
    {
      "_id": "68c0f00b2cc2cd421f617c7c",
      "type": 5,
      "type_id": "62a31031a4426cd04da6dcb4",
      "title": "缺陷",
      "project_id": "68c0e7ad2cc2cd421f613dbf",
      "position": 65536,
      "properties": {
        "board_id": null,
        "severity": null,
        "story_points": null,
        "iteration": null,
        "replay_version": [],
        "reappear_probability": null,
        "bug_type": null,
        "reason": null,
        "version": [],
        "solution": null,
        "replay_step": null,
        "zhichixuanzefu": null,
        "pingfen0621": null,
        "lianjie0621": null,
        "jindu0621_1": null,
        "estimated_workload": 6,
        "remaining_workload": 6,
        "workload_ss_emh": 8,
        "workload_ss_ermh": 8,
        "reported_workload": null,
        "workload": {
          "reported_total": 0,
          "remaining": 0,
          "estimated": {
            "duration": 0,
            "estimated_at": 1757474827,
            "estimated_by": null
          }
        },
        "operation_time": 1757474827,
        "swimlane_id": null,
        "entry_id": null,
        "entry_status": null,
        "entry_position": null,
        "phase": null,
        "workload_ss_armh": null,
        "workload_ss_pbr": 0,
        "xialaduoxuan": []
      },
      "parent_id": "68c0f00b2cc2cd421f617c7b",
      "parent_ids": [
        "68c0f00b2cc2cd421f617c79",
        "68c0f00b2cc2cd421f617c7a",
        "68c0f00b2cc2cd421f617c7b"
      ],
      "identifier": 19,
      "whole_identifier": "ZYK-19",
      "assignee": "18ca07872f354c03b111bc8e0a08aadc",
      "participants": [
        {
          "id": "18ca07872f354c03b111bc8e0a08aadc",
          "type": 1,
          "subscription": 40
        }
      ],
      "start": {
        "date": 1759593600,
        "with_time": 0
      },
      "due": {
        "date": 1760111999,
        "with_time": 0
      },
      "priority": null,
      "tags": [],
      "description": null,
      "phase": {
        "ref_id": null
      },
      "state_dwell_time": null,
      "state_id": "62a31031a4426cd04da6dcb6",
      "state_type": 1,
      "state_updated_at": 1757474827,
      "is_completed": 0,
      "completed_at": null,
      "completed_by": null,
      "comment_count": 0,
      "links": [],
      "attachment_count": 0,
      "user_group_participants": [],
      "source": {
        "type": 2,
        "from": "68c0e7ef2cc2cd421f613eaa"
      },
      "short_id": "xcbeqaE4",
      "created_at": 1757474827,
      "created_by": "18ca07872f354c03b111bc8e0a08aadc",
      "updated_at": 1757474827,
      "updated_by": "18ca07872f354c03b111bc8e0a08aadc",
      "is_deleted": 0,
      "is_archived": 0,
      "team": "62a31031fbadbd0d9adc51cf",
      "likes": [],
      "like_count": 0,
      "imported_at": null,
      "imported_by": null,
      "enter_iteration_at": null,
      "resources": [],
      "review_result_state": 0,
      "_updated_at": 1758681736552,
      "version_id": "68c0f00b2cc2cd421f617ccc",
      "version_identifier": 1,
      "relation_total": {
        "work_item": 2,
        "objective": 0,
        "idea": 0,
        "ticket": 0,
        "test_case": 0,
        "test_run": 0,
        "page": 0
      },
      "_v": 11,
      "permissions": "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "scope": {
        "project_template_type": "hybrid",
        "work_item_type": "62a31031a4426cd04da6dcb4"
      },
      "extend_property_keys": [
        "remaining_workload",
        "estimated_workload",
        "reported_workload",
        "progress_by_remaining",
        "child_progress",
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "sorted_property_keys": [
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "real_type_group": "bug",
      "type_group": 3,
      "link_count": 0,
      "quick_operation_actions": {
        "parent": 1,
        "state": 1,
        "assignee": 1,
        "start": 1,
        "due": 1,
        "priority": 1,
        "tag": 1,
        "copy": 1,
        "move": 1,
        "archive": 1,
        "active": 0,
        "delete": 1,
        "sprint": 0,
        "version": 1,
        "relate": 1,
        "board": 0
      },
      "version_name": "v1",
      "version_description": "Initialization & creation",
      "principal_version": "v1",
      "is_latest_version": 1,
      "property_permissions": {
        "title": 1,
        "identifier": 1,
        "type": 1,
        "state_id": 1,
        "assignee": 1,
        "parent_id": 1,
        "start": 1,
        "due": 1,
        "participants": 1,
        "created_at": 1,
        "created_by": 1,
        "updated_at": 1,
        "updated_by": 1,
        "completed_at": 1,
        "completed_by": 1,
        "archived_at": 1,
        "archived_by": 1,
        "deleted_at": 1,
        "deleted_by": 1,
        "state_dwell_time": 0,
        "state_type": 1,
        "attachments": 1,
        "review_result_state": 1,
        "project_id": 1,
        "reported_workload": 1,
        "remaining_workload": 1,
        "estimated_workload": 1,
        "progress_by_remaining": 1,
        "board_id": 1,
        "priority": 1,
        "severity": 1,
        "story_points": 1,
        "iteration": 1,
        "replay_version": 1,
        "reappear_probability": 1,
        "bug_type": 1,
        "reason": 1,
        "version": 1,
        "solution": 1,
        "tags": 1,
        "description": 1,
        "idea_count": 1,
        "work_item_count": 1,
        "ticket_count": 1,
        "test_case_count": 1,
        "objective_count": 1,
        "replay_step": 1,
        "phase": 1,
        "zhichixuanzefu": 1,
        "pingfen0621": 1,
        "lianjie0621": 1,
        "jindu0621_1": 1,
        "xialaduoxuan": 1,
        "child_progress": 1,
        "dependency_work_item": 1,
        "principal_version": 1,
        "deliverables": 1
      },
      "deliverables": {
        "total": 0,
        "submitted": 0
      },
      "child_ids": [
        "68c0f00b2cc2cd421f617c7d"
      ],
      "child_progress": 0,
      "child_completed_count": 0,
      "child_count": 1
    },
    {
      "_id": "68c0f00b2cc2cd421f617c7d",
      "type": 5,
      "type_id": "62a31031a4426cd04da6dcb4",
      "title": "缺陷",
      "project_id": "68c0e7ad2cc2cd421f613dbf",
      "position": 65536,
      "properties": {
        "board_id": null,
        "severity": null,
        "story_points": null,
        "iteration": null,
        "replay_version": [],
        "reappear_probability": null,
        "bug_type": null,
        "reason": null,
        "version": [],
        "solution": null,
        "replay_step": null,
        "zhichixuanzefu": null,
        "pingfen0621": null,
        "lianjie0621": null,
        "jindu0621_1": null,
        "estimated_workload": 2,
        "remaining_workload": 2,
        "workload_ss_emh": 2,
        "workload_ss_ermh": 2,
        "reported_workload": null,
        "workload": {
          "reported_total": 0,
          "remaining": 0,
          "estimated": {
            "duration": 0,
            "estimated_at": 1757474827,
            "estimated_by": null
          }
        },
        "operation_time": 1757474827,
        "swimlane_id": null,
        "entry_id": null,
        "entry_status": null,
        "entry_position": null,
        "phase": null,
        "xialaduoxuan": []
      },
      "parent_id": "68c0f00b2cc2cd421f617c7c",
      "parent_ids": [
        "68c0f00b2cc2cd421f617c79",
        "68c0f00b2cc2cd421f617c7a",
        "68c0f00b2cc2cd421f617c7b",
        "68c0f00b2cc2cd421f617c7c"
      ],
      "identifier": 20,
      "whole_identifier": "ZYK-20",
      "assignee": "b4c903caafbf40258c3449259286cbe5",
      "participants": [
        {
          "id": "18ca07872f354c03b111bc8e0a08aadc",
          "type": 1,
          "subscription": 40
        }
      ],
      "start": {
        "date": 1760371200,
        "with_time": 0
      },
      "due": {
        "date": 1760889599,
        "with_time": 0
      },
      "priority": null,
      "tags": [],
      "description": null,
      "phase": {
        "ref_id": null
      },
      "state_dwell_time": null,
      "state_id": "62a31031a4426cd04da6dcb6",
      "state_type": 1,
      "state_updated_at": 1757474827,
      "is_completed": 0,
      "completed_at": null,
      "completed_by": null,
      "comment_count": 0,
      "links": [],
      "attachment_count": 0,
      "user_group_participants": [],
      "source": {
        "type": 2,
        "from": "68c0e7ef2cc2cd421f613eab"
      },
      "short_id": "pCtMYI9G",
      "created_at": 1757474827,
      "created_by": "18ca07872f354c03b111bc8e0a08aadc",
      "updated_at": 1757474827,
      "updated_by": "18ca07872f354c03b111bc8e0a08aadc",
      "is_deleted": 0,
      "is_archived": 0,
      "team": "62a31031fbadbd0d9adc51cf",
      "likes": [],
      "like_count": 0,
      "imported_at": null,
      "imported_by": null,
      "enter_iteration_at": null,
      "resources": [],
      "review_result_state": 0,
      "_updated_at": 1758681736552,
      "version_id": "68c0f00b2cc2cd421f617ccd",
      "version_identifier": 1,
      "relation_total": {
        "work_item": 2,
        "objective": 0,
        "idea": 0,
        "ticket": 0,
        "test_case": 0,
        "test_run": 0,
        "page": 0
      },
      "_v": 11,
      "permissions": "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "scope": {
        "project_template_type": "hybrid",
        "work_item_type": "62a31031a4426cd04da6dcb4"
      },
      "extend_property_keys": [
        "remaining_workload",
        "estimated_workload",
        "reported_workload",
        "progress_by_remaining",
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "sorted_property_keys": [
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "real_type_group": "bug",
      "type_group": 3,
      "link_count": 0,
      "quick_operation_actions": {
        "parent": 1,
        "state": 1,
        "assignee": 1,
        "start": 1,
        "due": 1,
        "priority": 1,
        "tag": 1,
        "copy": 1,
        "move": 1,
        "archive": 1,
        "active": 0,
        "delete": 1,
        "sprint": 0,
        "version": 1,
        "relate": 1,
        "board": 0
      },
      "version_name": "v1",
      "version_description": "Initialization & creation",
      "principal_version": "v1",
      "is_latest_version": 1,
      "property_permissions": {
        "title": 1,
        "identifier": 1,
        "type": 1,
        "state_id": 1,
        "assignee": 1,
        "parent_id": 1,
        "start": 1,
        "due": 1,
        "participants": 1,
        "created_at": 1,
        "created_by": 1,
        "updated_at": 1,
        "updated_by": 1,
        "completed_at": 1,
        "completed_by": 1,
        "archived_at": 1,
        "archived_by": 1,
        "deleted_at": 1,
        "deleted_by": 1,
        "state_dwell_time": 0,
        "state_type": 1,
        "attachments": 1,
        "review_result_state": 1,
        "project_id": 1,
        "reported_workload": 1,
        "remaining_workload": 1,
        "estimated_workload": 1,
        "progress_by_remaining": 1,
        "board_id": 1,
        "priority": 1,
        "severity": 1,
        "story_points": 1,
        "iteration": 1,
        "replay_version": 1,
        "reappear_probability": 1,
        "bug_type": 1,
        "reason": 1,
        "version": 1,
        "solution": 1,
        "tags": 1,
        "description": 1,
        "idea_count": 1,
        "work_item_count": 1,
        "ticket_count": 1,
        "test_case_count": 1,
        "objective_count": 1,
        "replay_step": 1,
        "phase": 1,
        "zhichixuanzefu": 1,
        "pingfen0621": 1,
        "lianjie0621": 1,
        "jindu0621_1": 1,
        "xialaduoxuan": 1,
        "child_progress": 1,
        "dependency_work_item": 1,
        "principal_version": 1,
        "deliverables": 1
      },
      "deliverables": {
        "total": 0,
        "submitted": 0
      },
      "child_ids": [],
      "child_progress": 0,
      "child_completed_count": 0,
      "child_count": 0
    },
    {
      "_id": "68c0f0142cc2cd421f6182da",
      "type": 5,
      "type_id": "62a31031a4426cd04da6dcb4",
      "title": "缺陷",
      "project_id": "68c0e7ad2cc2cd421f613dbf",
      "position": 65536,
      "properties": {
        "board_id": null,
        "severity": null,
        "story_points": null,
        "iteration": null,
        "replay_version": [],
        "reappear_probability": null,
        "bug_type": null,
        "reason": null,
        "version": [],
        "solution": null,
        "replay_step": null,
        "zhichixuanzefu": null,
        "pingfen0621": null,
        "lianjie0621": null,
        "jindu0621_1": null,
        "estimated_workload": 6,
        "remaining_workload": 6,
        "workload_ss_emh": 8,
        "workload_ss_ermh": 8,
        "reported_workload": null,
        "workload": {
          "reported_total": 0,
          "remaining": 0,
          "estimated": {
            "duration": 0,
            "estimated_at": 1757474836,
            "estimated_by": null
          }
        },
        "operation_time": 1757474836,
        "swimlane_id": null,
        "entry_id": null,
        "entry_status": null,
        "entry_position": null,
        "phase": null,
        "workload_ss_armh": null,
        "workload_ss_pbr": 0,
        "xialaduoxuan": []
      },
      "parent_id": "68c0f0142cc2cd421f6182d9",
      "parent_ids": [
        "68c0f0142cc2cd421f6182d7",
        "68c0f0142cc2cd421f6182d8",
        "68c0f0142cc2cd421f6182d9"
      ],
      "identifier": 24,
      "whole_identifier": "ZYK-24",
      "assignee": "18ca07872f354c03b111bc8e0a08aadc",
      "participants": [
        {
          "id": "18ca07872f354c03b111bc8e0a08aadc",
          "type": 1,
          "subscription": 40
        }
      ],
      "start": {
        "date": 1759593600,
        "with_time": 0
      },
      "due": {
        "date": 1760111999,
        "with_time": 0
      },
      "priority": null,
      "tags": [],
      "description": null,
      "phase": {
        "ref_id": null
      },
      "state_dwell_time": null,
      "state_id": "62a31031a4426cd04da6dcb6",
      "state_type": 1,
      "state_updated_at": 1757474836,
      "is_completed": 0,
      "completed_at": null,
      "completed_by": null,
      "comment_count": 0,
      "links": [],
      "attachment_count": 0,
      "user_group_participants": [],
      "source": {
        "type": 2,
        "from": "68c0f00b2cc2cd421f617c7c"
      },
      "short_id": "YxFTUfnO",
      "created_at": 1757474836,
      "created_by": "18ca07872f354c03b111bc8e0a08aadc",
      "updated_at": 1757474836,
      "updated_by": "18ca07872f354c03b111bc8e0a08aadc",
      "is_deleted": 0,
      "is_archived": 0,
      "team": "62a31031fbadbd0d9adc51cf",
      "likes": [],
      "like_count": 0,
      "imported_at": null,
      "imported_by": null,
      "enter_iteration_at": null,
      "resources": [],
      "review_result_state": 0,
      "_updated_at": 1758681736552,
      "version_id": "68c0f0142cc2cd421f6182fb",
      "version_identifier": 1,
      "relation_total": {
        "work_item": 1,
        "objective": 0,
        "idea": 0,
        "ticket": 0,
        "test_case": 0,
        "test_run": 0,
        "page": 0
      },
      "_v": 11,
      "permissions": "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "scope": {
        "project_template_type": "hybrid",
        "work_item_type": "62a31031a4426cd04da6dcb4"
      },
      "extend_property_keys": [
        "remaining_workload",
        "estimated_workload",
        "reported_workload",
        "progress_by_remaining",
        "child_progress",
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "sorted_property_keys": [
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "real_type_group": "bug",
      "type_group": 3,
      "link_count": 0,
      "quick_operation_actions": {
        "parent": 1,
        "state": 1,
        "assignee": 1,
        "start": 1,
        "due": 1,
        "priority": 1,
        "tag": 1,
        "copy": 1,
        "move": 1,
        "archive": 1,
        "active": 0,
        "delete": 1,
        "sprint": 0,
        "version": 1,
        "relate": 1,
        "board": 0
      },
      "version_name": "v1",
      "version_description": "Initialization & creation",
      "principal_version": "v1",
      "is_latest_version": 1,
      "property_permissions": {
        "title": 1,
        "identifier": 1,
        "type": 1,
        "state_id": 1,
        "assignee": 1,
        "parent_id": 1,
        "start": 1,
        "due": 1,
        "participants": 1,
        "created_at": 1,
        "created_by": 1,
        "updated_at": 1,
        "updated_by": 1,
        "completed_at": 1,
        "completed_by": 1,
        "archived_at": 1,
        "archived_by": 1,
        "deleted_at": 1,
        "deleted_by": 1,
        "state_dwell_time": 0,
        "state_type": 1,
        "attachments": 1,
        "review_result_state": 1,
        "project_id": 1,
        "reported_workload": 1,
        "remaining_workload": 1,
        "estimated_workload": 1,
        "progress_by_remaining": 1,
        "board_id": 1,
        "priority": 1,
        "severity": 1,
        "story_points": 1,
        "iteration": 1,
        "replay_version": 1,
        "reappear_probability": 1,
        "bug_type": 1,
        "reason": 1,
        "version": 1,
        "solution": 1,
        "tags": 1,
        "description": 1,
        "idea_count": 1,
        "work_item_count": 1,
        "ticket_count": 1,
        "test_case_count": 1,
        "objective_count": 1,
        "replay_step": 1,
        "phase": 1,
        "zhichixuanzefu": 1,
        "pingfen0621": 1,
        "lianjie0621": 1,
        "jindu0621_1": 1,
        "xialaduoxuan": 1,
        "child_progress": 1,
        "dependency_work_item": 1,
        "principal_version": 1,
        "deliverables": 1
      },
      "deliverables": {
        "total": 0,
        "submitted": 0
      },
      "child_ids": [
        "68c0f0142cc2cd421f6182db"
      ],
      "child_progress": 0,
      "child_completed_count": 0,
      "child_count": 1
    },
    {
      "_id": "68c0f0142cc2cd421f6182db",
      "type": 5,
      "type_id": "62a31031a4426cd04da6dcb4",
      "title": "缺陷",
      "project_id": "68c0e7ad2cc2cd421f613dbf",
      "position": 65536,
      "properties": {
        "board_id": null,
        "severity": null,
        "story_points": null,
        "iteration": null,
        "replay_version": [],
        "reappear_probability": null,
        "bug_type": null,
        "reason": null,
        "version": [],
        "solution": null,
        "replay_step": null,
        "zhichixuanzefu": null,
        "pingfen0621": null,
        "lianjie0621": null,
        "jindu0621_1": null,
        "estimated_workload": 2,
        "remaining_workload": 2,
        "workload_ss_emh": 2,
        "workload_ss_ermh": 2,
        "reported_workload": null,
        "workload": {
          "reported_total": 0,
          "remaining": 0,
          "estimated": {
            "duration": 0,
            "estimated_at": 1757474836,
            "estimated_by": null
          }
        },
        "operation_time": 1757474836,
        "swimlane_id": null,
        "entry_id": null,
        "entry_status": null,
        "entry_position": null,
        "phase": null,
        "xialaduoxuan": []
      },
      "parent_id": "68c0f0142cc2cd421f6182da",
      "parent_ids": [
        "68c0f0142cc2cd421f6182d7",
        "68c0f0142cc2cd421f6182d8",
        "68c0f0142cc2cd421f6182d9",
        "68c0f0142cc2cd421f6182da"
      ],
      "identifier": 25,
      "whole_identifier": "ZYK-25",
      "assignee": "b4c903caafbf40258c3449259286cbe5",
      "participants": [
        {
          "id": "18ca07872f354c03b111bc8e0a08aadc",
          "type": 1,
          "subscription": 40
        }
      ],
      "start": {
        "date": 1760371200,
        "with_time": 0
      },
      "due": {
        "date": 1760889599,
        "with_time": 0
      },
      "priority": null,
      "tags": [],
      "description": null,
      "phase": {
        "ref_id": null
      },
      "state_dwell_time": null,
      "state_id": "62a31031a4426cd04da6dcb6",
      "state_type": 1,
      "state_updated_at": 1757474836,
      "is_completed": 0,
      "completed_at": null,
      "completed_by": null,
      "comment_count": 0,
      "links": [],
      "attachment_count": 0,
      "user_group_participants": [],
      "source": {
        "type": 2,
        "from": "68c0f00b2cc2cd421f617c7d"
      },
      "short_id": "tK7XfX1i",
      "created_at": 1757474836,
      "created_by": "18ca07872f354c03b111bc8e0a08aadc",
      "updated_at": 1757474836,
      "updated_by": "18ca07872f354c03b111bc8e0a08aadc",
      "is_deleted": 0,
      "is_archived": 0,
      "team": "62a31031fbadbd0d9adc51cf",
      "likes": [],
      "like_count": 0,
      "imported_at": null,
      "imported_by": null,
      "enter_iteration_at": null,
      "resources": [],
      "review_result_state": 0,
      "_updated_at": 1758681736552,
      "version_id": "68c0f0142cc2cd421f6182fc",
      "version_identifier": 1,
      "relation_total": {
        "work_item": 1,
        "objective": 0,
        "idea": 0,
        "ticket": 0,
        "test_case": 0,
        "test_run": 0,
        "page": 0
      },
      "_v": 11,
      "permissions": "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
      "scope": {
        "project_template_type": "hybrid",
        "work_item_type": "62a31031a4426cd04da6dcb4"
      },
      "extend_property_keys": [
        "remaining_workload",
        "estimated_workload",
        "reported_workload",
        "progress_by_remaining",
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "sorted_property_keys": [
        "board_id",
        "priority",
        "severity",
        "story_points",
        "iteration",
        "replay_version",
        "reappear_probability",
        "bug_type",
        "reason",
        "version",
        "solution",
        "tags",
        "description",
        "replay_step",
        "phase",
        "zhichixuanzefu",
        "pingfen0621",
        "lianjie0621",
        "jindu0621_1",
        "state_dwell_time",
        "xialaduoxuan"
      ],
      "real_type_group": "bug",
      "type_group": 3,
      "link_count": 0,
      "quick_operation_actions": {
        "parent": 1,
        "state": 1,
        "assignee": 1,
        "start": 1,
        "due": 1,
        "priority": 1,
        "tag": 1,
        "copy": 1,
        "move": 1,
        "archive": 1,
        "active": 0,
        "delete": 1,
        "sprint": 0,
        "version": 1,
        "relate": 1,
        "board": 0
      },
      "version_name": "v1",
      "version_description": "Initialization & creation",
      "principal_version": "v1",
      "is_latest_version": 1,
      "property_permissions": {
        "title": 1,
        "identifier": 1,
        "type": 1,
        "state_id": 1,
        "assignee": 1,
        "parent_id": 1,
        "start": 1,
        "due": 1,
        "participants": 1,
        "created_at": 1,
        "created_by": 1,
        "updated_at": 1,
        "updated_by": 1,
        "completed_at": 1,
        "completed_by": 1,
        "archived_at": 1,
        "archived_by": 1,
        "deleted_at": 1,
        "deleted_by": 1,
        "state_dwell_time": 0,
        "state_type": 1,
        "attachments": 1,
        "review_result_state": 1,
        "project_id": 1,
        "reported_workload": 1,
        "remaining_workload": 1,
        "estimated_workload": 1,
        "progress_by_remaining": 1,
        "board_id": 1,
        "priority": 1,
        "severity": 1,
        "story_points": 1,
        "iteration": 1,
        "replay_version": 1,
        "reappear_probability": 1,
        "bug_type": 1,
        "reason": 1,
        "version": 1,
        "solution": 1,
        "tags": 1,
        "description": 1,
        "idea_count": 1,
        "work_item_count": 1,
        "ticket_count": 1,
        "test_case_count": 1,
        "objective_count": 1,
        "replay_step": 1,
        "phase": 1,
        "zhichixuanzefu": 1,
        "pingfen0621": 1,
        "lianjie0621": 1,
        "jindu0621_1": 1,
        "xialaduoxuan": 1,
        "child_progress": 1,
        "dependency_work_item": 1,
        "principal_version": 1,
        "deliverables": 1
      },
      "deliverables": {
        "total": 0,
        "submitted": 0
      },
      "child_ids": [],
      "child_progress": 0,
      "child_completed_count": 0,
      "child_count": 0
    }
  ]

  export default tasks;
